# Generated by Django 4.1.7 on 2023-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('sbranch', models.CharField(max_length=50)),
                ('smob', models.IntegerField()),
                ('bookname', models.CharField(max_length=50)),
                ('bookno', models.IntegerField()),
            ],
        ),
    ]
